function xdc = xdc_lib(name)

%  Library of transducer information
%
%  Calling:
%           xdc = xdc_lib(name)
%
%  Parameters:
%           name            - Transducer name
%
%  Return:
%           xdc             - Structure of transducer properties with
%                             fields:
%                               name:       Transducer name
%                               type:       Transducer type
%                               n:          Number of elements
%                               pitch:      Center to center element distance
%                               kerf:       Interelement spacing
%                               width:      Element width
%                               height:     Element height
%                               r:          Radius of curvature
%                                           (curvilinear arrays only)
%                               fc:         Center frequency
%                               fbw:        Fractional bandwidth
%                               efocus:     Elevational focus
%
%  James Long, 03/09/2018

switch name
    case {'c52v', 'C52v', 'C52V', 'c5-2v', 'C5-2v', 'C5-2V'}
        xdc = struct('name', 'c52v',...
                     'type','curvilinear',...
                     'n', 128,...
                     'pitch', 0.000412,...
                     'kerf', 3.25e-5,...
                     'width', 0.0002925,...
                     'height', 0.0112,...
                     'r', 0.05,...
                     'fc', 3,...
                     'fbw', 0.7,...
                     'efocus', 0.060);
          
    case {'l124', '12l4', 'L124', '12L4', 'L12-4', 'l12-4'}
        xdc = struct('name', 'l124',...
                     'type','curvilinear',...
                     'n', 192,...
                     'pitch', 0.000267,...
                     'kerf', 3.5e-5,...
                     'width', 0.000232,...
                     'height', 0.007,...
                     'r', 0.025,...
                     'fc', 7.12,...
                     'fbw', 0.768,...
                     'efocus', 0.025);
                 
    case {'er7b', 'ER7B', 'er-7b'}
        warning('er7b information not confirmed!')
        xdc = struct('name', 'er7b',...
                     'type','curvilinear',...
                     'n', 192,...
                     'pitch', 0.00043,...
                     'kerf', 3e-5,...
                     'width', 0.0004,...
                     'height', 0.005,...
                     'r', 0.03,...
                     'fc', 5.16,...
                     'fbw', 0.768,...
                     'efocus', 0.025);
            
    case {'p42v', 'P4-2v', 'P42v', 'p4-2v', 'P4-2V'}
        xdc = struct('name', 'p42v',...
                     'type','linear',...
                     'n', 64,...
                     'pitch', 0.000315,...
                     'kerf', 2e-5,...
                     'width', 0.000295,...
                     'height', 0.0135,...
                     'fc', 2.5,...
                     'fbw', 0.93,...
                     'efocus', 0.060);
    
    case {'acunavp64', 'acunav64', 'an64', 'acunav10f'}
        xdc = struct('name', 'acunav64',...
                     'type', 'linear',...
                     'n', 64,...
                     'pitch', 0.00011,...
                     'kerf', 2e-5,...
                     'width', 9e-5,...
                     'height', 0.0025,...
                     'fc', 6,...
                     'fbw', 0.5,...
                     'efocus', 0.1);
                 
    otherwise
        error('Unsupported transducer name.')
end

end
